using Content.Client.Audio;
using Content.Shared._Sunrise.SunriseCCVars;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IConfigurationManager _cfg = default!;

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Control.AddOptionPercentSlider(
            SunriseCCVars.TTSVolume,
            SliderTts,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            SunriseCCVars.TTSRadioVolume,
            SliderTtsRadio,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionPercentSlider(
            SunriseCCVars.TTSAnnounceVolume,
            SliderTtsAnnounce,
            scale: ContentAudioSystem.TtsMultiplier);

        Control.AddOptionCheckBox(SunriseCCVars.TTSClientEnabled, TtsClientCheckBox);
        Control.AddOptionCheckBox(SunriseCCVars.TTSClientQueueEnabled, TtsClientCheckBoxQueue);
        Control.AddOptionCheckBox(SunriseCCVars.TTSRadioGhostEnabled, TtsRadioGhostCheckBox);

        Control.Initialize();
    }
}