using System;
using Content.Client.Computer;
using Content.Shared._Sunrise.Salvage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Salvage.UI;

[GenerateTypedNameReferences]
public sealed partial class SalvageQuotaConsoleWindow : FancyWindow
{
    public event Action<SalvageMissionType>? OnMissionTypeSelected;
    public event Action? OnActivateShuttle;

    private SalvageMissionType _selectedMissionType = SalvageMissionType.Money;

    public SalvageQuotaConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        MoneyMissionButton.OnPressed += _ => SelectMissionType(SalvageMissionType.Money);
        ResourcesMissionButton.OnPressed += _ => SelectMissionType(SalvageMissionType.Resources);
        ArtifactsMissionButton.OnPressed += _ => SelectMissionType(SalvageMissionType.Artifacts);
        MixedMissionButton.OnPressed += _ => SelectMissionType(SalvageMissionType.Mixed);
        
        ActivateShuttleButton.OnPressed += _ => OnActivateShuttle?.Invoke();
        
        UpdateButtonStyles();
    }

    private void SelectMissionType(SalvageMissionType missionType)
    {
        _selectedMissionType = missionType;
        OnMissionTypeSelected?.Invoke(missionType);
        UpdateButtonStyles();
        UpdateMissionLabel();
    }

    private void UpdateButtonStyles()
    {
        // Reset all buttons
        MoneyMissionButton.Modulate = Color.White;
        ResourcesMissionButton.Modulate = Color.White;
        ArtifactsMissionButton.Modulate = Color.White;
        MixedMissionButton.Modulate = Color.White;

        // Highlight selected button
        var selectedButton = _selectedMissionType switch
        {
            SalvageMissionType.Money => MoneyMissionButton,
            SalvageMissionType.Resources => ResourcesMissionButton,
            SalvageMissionType.Artifacts => ArtifactsMissionButton,
            SalvageMissionType.Mixed => MixedMissionButton,
            _ => MoneyMissionButton
        };

        selectedButton.Modulate = Color.LightBlue;
    }

    private void UpdateMissionLabel()
    {
        var missionText = _selectedMissionType switch
        {
            SalvageMissionType.Money => Loc.GetString("salvage-quota-mission-money-selected"),
            SalvageMissionType.Resources => Loc.GetString("salvage-quota-mission-resources-selected"),
            SalvageMissionType.Artifacts => Loc.GetString("salvage-quota-mission-artifacts-selected"),
            SalvageMissionType.Mixed => Loc.GetString("salvage-quota-mission-mixed-selected"),
            _ => Loc.GetString("salvage-quota-console-no-mission-selected")
        };

        SelectedMissionLabel.Text = missionText;
    }

    public void UpdateState(SalvageQuotaConsoleState state)
    {
        ActivateShuttleButton.Disabled = state.MissionActive || !state.ShuttleAvailable;
        
        if (state.MissionActive)
        {
            StatusLabel.Text = Loc.GetString("salvage-quota-console-status-mission-active");
            StatusLabel.FontColorOverride = Color.Orange;
        }
        else if (state.ShuttleAvailable)
        {
            StatusLabel.Text = Loc.GetString("salvage-quota-console-status-ready");
            StatusLabel.FontColorOverride = Color.Green;
        }
        else
        {
            StatusLabel.Text = Loc.GetString("salvage-quota-console-status-shuttle-unavailable");
            StatusLabel.FontColorOverride = Color.Red;
        }
    }
}