using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using System;

namespace Content.Client.Administration.UI.Dialogs
{
    [GenerateTypedNameReferences]
    public sealed partial class CoordinateInputDialog : FancyWindow
    {
        public event Action<float, float>? OnCoordinatesConfirmed;

        public CoordinateInputDialog()
        {
            RobustXamlLoader.Load(this);

            ConfirmButton.OnPressed += _ => OnConfirmPressed();
            CancelButton.OnPressed += _ => Close();
        }

        private void OnConfirmPressed()
        {
            var x = (float)XCoordinate.Value;
            var y = (float)YCoordinate.Value;
            
            OnCoordinatesConfirmed?.Invoke(x, y);
            Close();
        }
    }
}