- type: job
  id: SecurityOfficer
  name: job-name-security
  description: job-description-security
  playTimeTracker: JobSecurityOfficer
  alternativeTitles:
    - title: job-alt-title-security-officer-corporal-first-class
      playtimeRequirement: 36000 # 10 hours as Security Officer
    - title: job-alt-title-security-officer-senior-corporal
      playtimeRequirement: 360000 # 100 hours as Security Officer
    - title: job-alt-title-security-officer-master-corporal
      playtimeRequirement: 900000 # 250 hours as Security Officer
    - title: job-alt-title-security-officer-sergeant
      playtimeRequirement: 1800000 # 500 hours as Security Officer
  requirements:
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 #5 hrs # Sunrise-RoleTime
  startingGear: SecurityOfficerGear
  icon: "JobIconSecurityOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: 10
  access:
  - Security
  - Brig
#  - Maintenance #Sunrise-Edit
  - Service
  - External
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: SecurityOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: SecurityPDA
    ears: ClothingHeadsetSecurity
    head: ClothingHeadHelmetBasic
    gloves: ClothingHandsGlovesColorBlack
  storage:
    back:
    - Flash
#    - MagazineGlock22 # Sunrise-Edit

- type: chameleonOutfit
  id: SecurityOfficerChameleonOutfit
  job: SecurityOfficer
  hasMindShield: true
  equipment:
    head: ClothingHeadHatBeretSecurity
    mask: ClothingMaskGasSecurity
    neck: Dinkystar
    gloves: ClothingHandsGlovesColorBlack
