- type: job
  id: Warden
  name: job-name-warden
  description: job-description-warden
  playTimeTracker: JobWarden
  alternativeTitles:
    - title: job-alt-title-warden-first-sergeant
      playtimeRequirement: 180000 # 50 hours as Warden
    - title: job-alt-title-warden-lieutenant
      playtimeRequirement: 360000 # 100 hours as Warden
    - title: job-alt-title-warden-captain
      playtimeRequirement: 900000 # 250 hours as Warden
    - title: job-alt-title-warden-major
      playtimeRequirement: 1800000 # 500 hours as Warden
    - title: job-alt-title-warden-lieutenant-colonel
      playtimeRequirement: 3600000 # 1000 hours as Warden
  requirements:
    - !type:RoleTimeRequirement
      role: JobSecurityOfficer
      time: 54000 #15 hrs # Sunrise-RoleTime
  weight: 5
  startingGear: WardenGear
  icon: "JobIconWarden"
  supervisors: job-supervisors-hos
  canBeAntag: false
  displayWeight: 70  # Sunrise
  access:
  - Security
  - Brig
  - Armory
#  - Maintenance #Sunrise-Edit
  - Service
  - External
  - Detective
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  speciesBlacklist:
  - Vox

- type: startingGear
  id: WardenGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: WardenPDA
    ears: ClothingHeadsetSecurity
  storage:
    back:
    - Flash
#    - MagazineGlock22 # Sunrise-Edit

- type: chameleonOutfit
  id: WardenChameleonOutfit
  job: Warden
  hasMindShield: true
  equipment:
    head: ClothingHeadHatWarden
    mask: ClothingMaskGasSecurity
    outerClothing: ClothingOuterCoatWarden
    jumpsuit: ClothingUniformJumpsuitWarden
    neck: Dinkystar
    belt: ClothingBeltSecurity
    gloves: ClothingHandsGlovesCombat
    shoes: ClothingShoesBootsJack
