using Content.Client.Pinpointer.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class NavigatorUiFragment : BoxContainer
{
    public NavMapControl? NavMap;
    private readonly SpriteSystem _spriteSystem;
    private Texture? _blipTexture;

    public NavigatorUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        
        _spriteSystem = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        _blipTexture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(new ResPath("/Textures/Interface/NavMap/beveled_circle.png")));
    }

    public void Setup(EntityUid? owner)
    {
        NavMap = new NavMapControl();
        NavMap.Owner = owner;
        NavMap.HorizontalExpand = true;
        NavMap.VerticalExpand = true;

        NavMapContainer.AddChild(NavMap);
    }

    public void UpdateState(EntityUid? mapUid, string stationName, EntityCoordinates? ownerCoordinates = null)
    {
        StationNameLabel.Text = stationName;

        if (NavMap != null && mapUid != null)
        {
            NavMap.MapUid = mapUid;
            
            // Clear any previous tracked entities
            NavMap.TrackedEntities.Clear();
            
            // Add owner location if available
            if (ownerCoordinates != null && _blipTexture != null)
            {
                // Use a special key for the owner position
                var ownerKey = new NetEntity(0);
                NavMap.TrackedEntities[ownerKey] = new NavMapBlip(
                    ownerCoordinates.Value, 
                    _blipTexture, 
                    Color.Red, // Red color to make it stand out
                    false, // Don't blink
                    false, // Not selectable
                    1.5f // Slightly larger scale
                );
            }
        }
    }
}
