using System.Numerics;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class SignatureWidget : PanelContainer
{
    public float Orientation
    {
        get => SignatureLabel.Orientation;
        set => SignatureLabel.Orientation = value;
    }

    public SignatureDisplayInfo SignatureInfo {
        set {
            var displayText = $"{value.SignerName} [{value.Timestamp}]";
            SignatureLabel.Text = displayText;
            SignatureLabel.FontColorOverride = value.SignerColor;
            ModulateSelfOverride = value.SignerColor;
        }
    }

    public SignatureWidget()
    {
        RobustXamlLoader.Load(this);
        
        // Set a simple background for signatures (different from stamps)
        var solidBackground = new StyleBoxFlat
        {
            BackgroundColor = Color.FromHex("#F5F5DC") with { A = 0.8f }, // Beige background
            BorderColor = Color.DarkBlue with { A = 0.6f },
            BorderThickness = new Thickness(1)
        };
        PanelOverride = solidBackground;
    }
}