using System.Numerics;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class SignatureLabel : Label
{
    public float Orientation;

    public SignatureLabel()
    {
        RobustXamlLoader.Load(this);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        handle.SetTransform(GlobalPosition * UIScale, Orientation, Vector2.One);
        base.Draw(handle);

        // Restore a sane transform
        handle.SetTransform(Matrix3x2.Identity);
    }
}