- type: job
  id: Chef
  name: job-name-chef
  description: job-description-chef
  playTimeTracker: JobChef
  alternativeTitles:
    - title: job-alt-title-chef-cook
      playtimeRequirement: 3600 # 1 hour as Chef
    - title: job-alt-title-chef-culinary-artist
      playtimeRequirement: 7200 # 2 hours as Chef
    - title: job-alt-title-chef-gastronomer
      playtimeRequirement: 14400 # 4 hours as Chef
  requirements:
    - !type:DepartmentTimeRequirement
      department: Civilian
      time: 3600 #1 hrs # Sunrise-RoleTime
  startingGear: ChefGear
  icon: "JobIconChef"
  supervisors: job-supervisors-hop
  access:
  - Service
  - Maintenance
  - Kitchen
  extendedAccess:
  - Hydroponics
  - Bar

- type: startingGear
  id: ChefGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: ChefPDA
    ears: ClothingHeadsetService
    belt: ClothingBeltChefFilled
  #storage:
    #back:
    #- Stuff

- type: chameleonOutfit
  id: ChefChameleonOutfit
  job: Chef
  equipment:
    head: ClothingHeadHatChef
    eyes: ClothingEyesGlassesCheapSunglasses
    mask: ClothingMaskItalianMoustache
    neck: ClothingNeckScarfStripedBrown
    outerClothing: ClothingOuterJacketChef
    gloves: ClothingHandsGlovesColorWhite
    shoes: ClothingShoesChef
